version: '3'

services:
  bot:
    build:
      context: .
    volumes:
      - .:/code
      - sqlite_data:/code/db
    env_file:
      - .env
    ports:
      - "8077:8000"
    command: |
      bash -c "
        python3 manage.py migrate &
        python3 manage.py runserver 0.0.0.0:8000 &
        wait
      "
    networks:
      - bot_network

  bot_service:
    build:
      context: .
    command: python3 bot.py
    volumes:
      - .:/code
    environment:
      - ENV_VAR=value
    depends_on:
      - bot
    restart: always
    networks:
      - bot_network

volumes:
  sqlite_data:

networks:
  bot_network:
    driver: bridge
